language: cpp
compiler: 
 - gcc
 - clang
# Change this to your needs
before_install:
 - sudo apt-get install texinfo
 - sudo pip install cpp-coveralls
 - wget ftp://ftp.gnu.org/gnu/libmicrohttpd/libmicrohttpd-0.9.37.tar.gz
 - tar -xvzf libmicrohttpd-0.9.37.tar.gz
 - cd libmicrohttpd-0.9.37
 - ./configure --prefix=/usr
 - make
 - sudo make install
 - cd ..
script:
 - ./bootstrap
 - mkdir build
 - cd build
 - ../configure --enable-gcov
 - make
 - make check
 - cd ..
   # - rm -rf build
   # - mkdir build
   # - cd build
   # - ../configure --enable-cpp11
   # - make
   # - make check
   # - cd ..
after_success:
  - coveralls --exclude lib --exclude tests --gcov-options '\-lp'
