language: cpp
compiler: 
 - gcc
 - clang
# Change this to your needs
before_install:
 - sudo apt-get install texinfo
 - wget http://199.231.187.83/resources/libmicrohttpd-0.9.26.tar.gz
 - tar -xvzf libmicrohttpd-0.9.26.tar.gz
 - cd libmicrohttpd-0.9.26
 - ./configure --prefix=/usr
 - make
 - sudo make install
 - cd ..
script: ./bootstrap && mkdir build && cd build && ../configure && make && make check
