language: cpp
compiler: 
 - gcc
 - clang
env:
 - CONF_COMMAND=../configure --enable-debug; DEBUG="debug"
 - CONF_COMMAND=../configure
before_install:
 - sudo apt-get install texinfo
 - sudo pip install cpp-coveralls
 - wget ftp://ftp.gnu.org/gnu/libmicrohttpd/libmicrohttpd-0.9.37.tar.gz
 - tar -xvzf libmicrohttpd-0.9.37.tar.gz
 - cd libmicrohttpd-0.9.37
 - ./configure --prefix=/usr
 - make
 - sudo make install
 - cd ..
script:
 - ./bootstrap
 - mkdir build
 - cd build
 - $(echo $CONF_COMMAND)
 - make
 - make check
after_success:
  - if [ $DEBUG = "debug" ]; then coveralls --no-gcov --extension cpp --build-root src/ --exclude lib --exclude tests --gcov-options '\-lp'; fi
matrix:
  exclude:
    - compiler: clang
      env: CONF_COMMAND=../configure --enable-debug; DEBUG="debug"
